import { Lightbulb, Sparkles } from "lucide-react";
import { db } from "@/lib/db";
import { requireRole } from "@/lib/auth";
import { generateOwnerSuggestions } from "@/lib/ai-report";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const PRIORITY_STYLE: Record<string, string> = {
  high: "bg-red-100 text-red-800 dark:bg-red-950 dark:text-red-300",
  medium: "bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300",
  low: "bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300",
};

export default async function OwnerSuggestionsPage() {
  const owner = await requireRole("business_owner");

  const businesses = await db.business.findMany({
    where: { ownerId: owner.id },
    include: { inspections: { include: { violations: true } }, documents: true },
  });

  const allSuggestions = businesses.flatMap((b) => {
    const expiredDocs = b.documents.filter((d) => d.expiresAt && d.expiresAt < new Date()).length;
    const suggestions = generateOwnerSuggestions({
      businessName: b.name,
      violations: b.inspections.flatMap((i) => i.violations.map((v) => ({ type: v.type, severity: v.severity }))),
      currentTier: b.riskTier,
      expiredDocs,
    });
    return suggestions.map((s) => ({ ...s, businessName: b.name }));
  });

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">AI Improvement Suggestions</h1>
        <p className="text-sm text-muted-foreground">
          Plain-language, actionable tips generated from your inspection history. No jargon.
        </p>
      </div>

      {allSuggestions.length === 0 ? (
        <Card>
          <CardContent className="flex h-48 flex-col items-center justify-center text-center">
            <Lightbulb className="h-10 w-10 text-muted-foreground" />
            <p className="mt-3 font-medium">No suggestions yet</p>
            <p className="text-sm text-muted-foreground">Tips appear once you have inspection history.</p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4 md:grid-cols-2">
          {allSuggestions.map((s, i) => (
            <Card key={i}>
              <CardContent className="space-y-3 p-5">
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-start gap-3">
                    <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                      <Sparkles className="h-4 w-4" />
                    </div>
                    <div>
                      <p className="font-medium">{s.title}</p>
                      <p className="text-xs text-muted-foreground">{s.businessName}</p>
                    </div>
                  </div>
                  <Badge variant="outline" className={PRIORITY_STYLE[s.priority]}>
                    {s.priority}
                  </Badge>
                </div>
                <p className="text-sm text-muted-foreground">{s.body}</p>
                <p className="rounded-lg bg-muted/40 px-3 py-2 text-xs font-medium text-foreground/80">{s.impact}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <p className="text-xs text-muted-foreground">
        Suggestions are generated by the same transparent model behind your score — every tip maps to a real finding on
        your record.
      </p>
    </div>
  );
}
